ElasticSearch Debug Integration
sifophp/sifo-common-instance pull request #1
Opened 2017-08-01 09:51 UTC by marcossegovia

Hi @obokaman-com 
We've come up with the implementation of an appropriate debug template for an ElasticSearch Client, maybe it is useful for the Common-Sifo dependency.

2017-08-23 16:39 UTC, obokaman-com requested changes
Solucionado el `default|false` que comento arriba, creo que se puede integrar sin problemas.

2017-08-23 16:39 UTC, obokaman-com commented on templates/debug/mini_debug.tpl
> +			{if $debug.times.elastic_search}
Igual que en el caso de los errores, valdría la pena añadir un `|default:false`.

2017-08-24 09:29 UTC, marcossegovia commented
@obokaman-com changes added !

2017-08-24 11:31 UTC, obokaman-com approved these changes

2017-08-24 11:33 UTC, merged