Changes for allow languages heritage.
sifophp/sifo-common-instance pull request #2
Opened 2019-02-26 14:56 UTC by mangasf

Two changes applied:

- Change getTranslations method for get translation of parent lang when we not have the lang translation.
- Changes in status template for show in the translations tool base translations.

2019-02-26 22:14 UTC, obokaman-com requested changes
Viendo los cambios, imagino que sólo se generan los config con los contenidos que se hereden entre idiomas. El funcionamiento respecto a la herencia entre instancias sigue basándose en el uso del include entre diferentes ficheros de traducciones, cierto?

2019-02-26 22:14 UTC, obokaman-com commented on models/i18n/translator.php
> +    IF(t1.translation IS NOT NULL, t1.translation, t2.translation) AS translation,
```suggestion
    IFNULL(t1.translation, t2.translation) AS translation,
```

2019-02-26 22:14 UTC, obokaman-com commented on models/i18n/translator.php
> +    IF(t1.translation IS NOT NULL, t1.translation, t2.translation) AS translation,
Lo mismo es aplicable a `author` y `modified`

2019-03-06 12:05 UTC, mangasf commented
@obokaman-com Actualizada la PR para tener en cuenta también la herencia de instancias.

2019-03-12 22:55 UTC, merged

2019-03-12 22:56 UTC, obokaman-com commented
Integrando!